# Generated by Django 4.1.3 on 2022-12-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="radioactiveSourcePackageReception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.CharField(max_length=120)),
                ("remarks_description", models.TextField()),
                ("supplier", models.CharField(max_length=120)),
                ("receptionDateTime", models.DateTimeField()),
                ("radionuclide", models.CharField(max_length=20)),
                ("halfLife", models.DurationField()),
                (
                    "requestedActivity",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "receivedActivity",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "radiationLevel_1m",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "radiationLevel_0m",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("measurementEquipment", models.CharField(max_length=50)),
                ("brandModel", models.CharField(max_length=120)),
                ("serialNumberEquipment", models.CharField(max_length=50)),
                ("serialNumberDetector", models.CharField(max_length=50)),
                ("detectorCalibrationDate", models.DateTimeField()),
                ("calibrationFactor", models.CharField(max_length=50)),
                ("zoneLocation", models.TextField()),
                ("rubbedSurface", models.TextField()),
                ("smearReading", models.DecimalField(decimal_places=2, max_digits=8)),
                ("equipmentUsed", models.CharField(max_length=50)),
                ("brandModel_smearReading", models.CharField(max_length=120)),
                ("serialNumberEquipment_smearReading", models.CharField(max_length=50)),
                ("serialNumberDetector_smearReading", models.CharField(max_length=50)),
                ("packageAcceptanceReception", models.CharField(max_length=20)),
                ("reasonsAcceptanceReception", models.TextField()),
                ("nameMedPhys", models.CharField(max_length=50)),
            ],
        ),
    ]
